-- CROSSFADE physical data model (MySQL 8).
-- Generated by project1/scripts/build_ddl.py from the requirements analysis; do not edit by hand.


DROP SCHEMA IF EXISTS crossfade;
CREATE SCHEMA crossfade DEFAULT CHARACTER SET utf8mb4;
USE crossfade;

CREATE TABLE artist (
  artist_id MEDIUMINT UNSIGNED NOT NULL,
  stage_name VARCHAR(64) NOT NULL,
  country CHAR(2),
  joined_date DATE NOT NULL,
  payout_rate DECIMAL(5,5) NOT NULL,
  verified BIT(1) NOT NULL,
  PRIMARY KEY (artist_id),
  UNIQUE KEY uq_artist_stage_name (stage_name),
  CONSTRAINT ck_artist_1 CHECK (payout_rate > 0)
) ENGINE=InnoDB;

CREATE TABLE track (
  track_id INT UNSIGNED NOT NULL,
  artist_id MEDIUMINT UNSIGNED NOT NULL,
  title VARCHAR(128) NOT NULL,
  duration SMALLINT UNSIGNED NOT NULL,
  release_date DATE NOT NULL,
  audio_checksum BINARY(32) NOT NULL,
  ingest_status ENUM('awaiting scoring', 'scored', 'rejected') NOT NULL,
  PRIMARY KEY (track_id),
  UNIQUE KEY uq_track_audio_checksum (audio_checksum),
  CONSTRAINT fk_track_artist FOREIGN KEY (artist_id) REFERENCES artist (artist_id),
  CONSTRAINT ck_track_1 CHECK (duration > 0)
) ENGINE=InnoDB;

CREATE TABLE genre (
  genre_id TINYINT UNSIGNED NOT NULL,
  name VARCHAR(9) NOT NULL,
  description VARCHAR(80),
  PRIMARY KEY (genre_id),
  UNIQUE KEY uq_genre_name (name),
  CONSTRAINT ck_genre_1 CHECK (genre_id BETWEEN 0 AND 9)
) ENGINE=InnoDB;

CREATE TABLE listener (
  listener_id INT UNSIGNED NOT NULL,
  email VARCHAR(254) NOT NULL,
  display_name VARCHAR(32) NOT NULL,
  plan_tier ENUM('free', 'standard', 'premium') NOT NULL,
  signup_date DATE NOT NULL,
  PRIMARY KEY (listener_id),
  UNIQUE KEY uq_listener_email (email)
) ENGINE=InnoDB;

CREATE TABLE scoring_model (
  model_id TINYINT UNSIGNED NOT NULL,
  version_label VARCHAR(32) NOT NULL,
  fusion_type ENUM('concat', 'gated') NOT NULL,
  embedding_dimension SMALLINT UNSIGNED NOT NULL,
  segment_length TINYINT UNSIGNED NOT NULL,
  training_corpus VARCHAR(16) NOT NULL,
  holdout_accuracy DECIMAL(5,4) NOT NULL,
  deployed_on DATE NOT NULL,
  PRIMARY KEY (model_id),
  UNIQUE KEY uq_scoring_model_version_label (version_label),
  CONSTRAINT ck_scoring_model_1 CHECK (holdout_accuracy BETWEEN 0 AND 1),
  CONSTRAINT ck_scoring_model_2 CHECK (segment_length > 0),
  CONSTRAINT ck_scoring_model_3 CHECK (embedding_dimension > 0)
) ENGINE=InnoDB;

CREATE TABLE station (
  station_id INT UNSIGNED NOT NULL,
  listener_id INT UNSIGNED NOT NULL,
  model_id TINYINT UNSIGNED NOT NULL,
  name VARCHAR(64) NOT NULL,
  minimum_ambiguity DECIMAL(3,2) NOT NULL,
  maximum_ambiguity DECIMAL(3,2) NOT NULL,
  created_on DATE NOT NULL,
  PRIMARY KEY (station_id),
  CONSTRAINT fk_station_listener FOREIGN KEY (listener_id) REFERENCES listener (listener_id),
  CONSTRAINT fk_station_scoring_model FOREIGN KEY (model_id) REFERENCES scoring_model (model_id),
  CONSTRAINT ck_station_1 CHECK (minimum_ambiguity BETWEEN 0 AND 1),
  CONSTRAINT ck_station_2 CHECK (maximum_ambiguity BETWEEN 0 AND 1),
  CONSTRAINT ck_station_3 CHECK (minimum_ambiguity <= maximum_ambiguity)
) ENGINE=InnoDB;

CREATE TABLE track_score (
  track_id INT UNSIGNED NOT NULL,
  model_id TINYINT UNSIGNED NOT NULL,
  genre_id TINYINT UNSIGNED NOT NULL COMMENT 'Derived: genre with the highest probability in this score''s Genre Probability rows (I3)',
  top_probability DECIMAL(5,4) NOT NULL COMMENT 'Derived: largest of this score''s ten probabilities (I3)',
  posterior_entropy DECIMAL(5,4) NOT NULL COMMENT 'Derived: Shannon entropy of the ten probabilities / log(10) (I3)',
  model_divergence DECIMAL(5,4) COMMENT 'Derived: mean Jensen-Shannon divergence from the other models'' distributions for this track (I3)',
  segment_variance DECIMAL(4,4),
  scored_on DATETIME NOT NULL,
  PRIMARY KEY (track_id, model_id),
  CONSTRAINT fk_track_score_track FOREIGN KEY (track_id) REFERENCES track (track_id),
  CONSTRAINT fk_track_score_scoring_model FOREIGN KEY (model_id) REFERENCES scoring_model (model_id),
  CONSTRAINT fk_track_score_genre FOREIGN KEY (genre_id) REFERENCES genre (genre_id),
  CONSTRAINT ck_track_score_1 CHECK (top_probability BETWEEN 0 AND 1),
  CONSTRAINT ck_track_score_2 CHECK (posterior_entropy BETWEEN 0 AND 1),
  CONSTRAINT ck_track_score_3 CHECK (model_divergence IS NULL OR model_divergence BETWEEN 0 AND 1),
  CONSTRAINT ck_track_score_4 CHECK (segment_variance IS NULL OR segment_variance BETWEEN 0 AND 0.25)
) ENGINE=InnoDB;

CREATE TABLE play (
  listener_id INT UNSIGNED NOT NULL,
  track_id INT UNSIGNED NOT NULL,
  played_at DATETIME NOT NULL,
  station_id INT UNSIGNED,
  seconds_played SMALLINT UNSIGNED NOT NULL,
  completed BIT(1) NOT NULL COMMENT 'Derived: 1 exactly when seconds_played = track.duration (I7)',
  reaction ENUM('saved', 'skipped'),
  royalty_amount DECIMAL(5,5) NOT NULL COMMENT 'Snapshot: artist payout_rate at play time if seconds_played >= 30, else 0 (I7)',
  PRIMARY KEY (listener_id, track_id, played_at),
  CONSTRAINT fk_play_listener FOREIGN KEY (listener_id) REFERENCES listener (listener_id),
  CONSTRAINT fk_play_track FOREIGN KEY (track_id) REFERENCES track (track_id),
  CONSTRAINT fk_play_station FOREIGN KEY (station_id) REFERENCES station (station_id),
  CONSTRAINT ck_play_1 CHECK (royalty_amount >= 0)
) ENGINE=InnoDB;

CREATE TABLE station_blend (
  station_id INT UNSIGNED NOT NULL,
  genre_id TINYINT UNSIGNED NOT NULL,
  weight DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (station_id, genre_id),
  CONSTRAINT fk_station_blend_station FOREIGN KEY (station_id) REFERENCES station (station_id),
  CONSTRAINT fk_station_blend_genre FOREIGN KEY (genre_id) REFERENCES genre (genre_id),
  CONSTRAINT ck_station_blend_1 CHECK (weight > 0 AND weight <= 1)
) ENGINE=InnoDB;

CREATE TABLE genre_probability (
  track_id INT UNSIGNED NOT NULL,
  model_id TINYINT UNSIGNED NOT NULL,
  genre_id TINYINT UNSIGNED NOT NULL,
  probability DECIMAL(5,4) NOT NULL,
  PRIMARY KEY (track_id, model_id, genre_id),
  CONSTRAINT fk_genre_probability_track_score FOREIGN KEY (track_id, model_id) REFERENCES track_score (track_id, model_id),
  CONSTRAINT fk_genre_probability_genre FOREIGN KEY (genre_id) REFERENCES genre (genre_id),
  CONSTRAINT ck_genre_probability_1 CHECK (probability BETWEEN 0 AND 1)
) ENGINE=InnoDB;
